[package]
name = "rust-cli-music-player"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.17"
crossterm = "0.27"
walkdir = "2.4"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
ratatui = "0.26"

